spring.application.name=shafe

# Enable DEBUG/TRACE for Spring Web and WebSocket routing
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.socket=TRACE

# Enable DEBUG for Tomcat's internal WebSocket handling
logging.level.org.apache.tomcat.websocket=DEBUG

# Show your application's package logs
logging.level.com.nixxrazcorp.shafe=DEBUG